#!/bin/bash

if echo "$1" | grep -Eq '.*'; then
	echo "$1" | grep -Eq '.*([\.]?matrix\.org)(\/_matrix)\/.*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*([\.]?prismic\.io).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*([\.]?gitlab\.com).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*([\.]?gcsip\.com).*[\?|&]ref[\_]?=[^\/|\?|&]*.*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*([\.]?cloudflare\.com).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(myaccount.google\.[a-zA-Z]{2,}).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*([\.]?tangerine\.ca).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*bugtracker\.fairphone\.com\/.*[\?|&]ref[\_]?=[^\/|\?|&]*.*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(comment-cdn\.9gag\.com).*(\/comment-list.json\?).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(battle\.net\/login).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(blizzard\.com\/oauth2).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(streamguard\.cc).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(clastarti\.cc).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(kreditkarten-banking\.lbb\.de).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(facebook\.)\w{2,}.*(\/groups\/member_bio\/bio_dialog\/).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*([\.]?tinkoff\.ru).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(cyberport\.de).*(\/adscript\.php).*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*(\/refs\/switch).*\?.*(%3F)?[\?|&]?ref[\_]?=.*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '.*tweakers\.net\/ext\/lt\.dsp\?.*(%3F)?[\?|&]?ref[\_]?=.*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '(https:\/\/|http:\/\/)git\..*(\.[a-zA-Z]{2,}).*\/commit\/.*\/pipelines\?.*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '(https:\/\/|http:\/\/)git\..*(\.[a-zA-Z]{2,}).*\/.*\/-\/branches\?.*' && UseGenericRegex='false'
	echo "$1" | grep -Eq '(https:\/\/|http:\/\/)([a-zA-Z0-9-]*\.)?(amazon)(\.[a-zA-Z]{2,}).*\/message-us\?.*' && UseGenericRegex='false'
	[ "$UseGenericRegex" != 'false' ] && UseGenericRegex='true'
fi
